# -*- coding: utf-8 -*-
f=open(r'C:\Users\mezan\source\repos\BuildForce\BuildForce\Views\MorePage.xaml','w',encoding='utf-8',newline='\n')
f.write('<?xml version="1.0" encoding="utf-8" ?>\n')
f.write('<ContentPage x:Class="BuildForce.Views.MorePage"\n')
f.write('    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"\n')
f.write('    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"\n')
f.write('    Shell.NavBarIsVisible="False" Shell.TabBarIsVisible="True"\n')
f.write('    BackgroundColor="#0d1117">\n')
f.write('  <ScrollView>\n')
f.write('    <VerticalStackLayout Spacing="0">\n')
f.write('      <Grid Padding="20,52,20,24">\n')
f.write('        <Grid.ColumnDefinitions>\n')
f.write('          <ColumnDefinition Width="Auto"/>\n')
f.write('          <ColumnDefinition Width="*"/>\n')
f.write('          <ColumnDefinition Width="Auto"/>\n')
f.write('        </Grid.ColumnDefinitions>\n')
f.write('        <Frame Grid.Column="0" WidthRequest="62" HeightRequest="62" CornerRadius="31" BackgroundColor="#f0a500" BorderColor="#f0a500" Padding="0" HasShadow="False">\n')
f.write('          <Label Text="{Binding UserInitials}" FontSize="22" FontAttributes="Bold" TextColor="#0d1117" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('        </Frame>\n')
f.write('        <VerticalStackLayout Grid.Column="1" Margin="14,0,0,0" VerticalOptions="Center" Spacing="3">\n')
f.write('          <Label Text="{Binding UserName}" FontSize="17" FontAttributes="Bold" TextColor="White"/>\n')
f.write('          <Label Text="{Binding CompanyName}" FontSize="13" TextColor="#7d8590"/>\n')
f.write('          <Frame BackgroundColor="#1f1a00" BorderColor="#f0a500" CornerRadius="10" Padding="8,3" HasShadow="False" HorizontalOptions="Start">\n')
f.write('            <Label Text="{Binding PlanName}" FontSize="11" TextColor="#f0a500" FontAttributes="Bold"/>\n')
f.write('          </Frame>\n')
f.write('        </VerticalStackLayout>\n')
f.write('        <Label Grid.Column="2" Text="&#x203A;" FontSize="26" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('      </Grid>\n')
f.write('      <Grid ColumnDefinitions="*,*,*" Margin="16,0,16,24" ColumnSpacing="10">\n')
f.write('        <Frame Grid.Column="0" BackgroundColor="#161b22" BorderColor="#f0a500" CornerRadius="16" Padding="14,12" HasShadow="False">\n')
f.write('          <VerticalStackLayout Spacing="2" HorizontalOptions="Center">\n')
f.write('            <Label Text="{Binding ActiveProjects}" FontSize="26" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="Center"/>\n')
f.write('            <Label Text="Projects" FontSize="11" TextColor="#7d8590" HorizontalOptions="Center"/>\n')
f.write('          </VerticalStackLayout>\n')
f.write('        </Frame>\n')
f.write('        <Frame Grid.Column="1" BackgroundColor="#161b22" BorderColor="#10b981" CornerRadius="16" Padding="14,12" HasShadow="False">\n')
f.write('          <VerticalStackLayout Spacing="2" HorizontalOptions="Center">\n')
f.write('            <Label Text="{Binding PendingInvoices}" FontSize="26" FontAttributes="Bold" TextColor="#10b981" HorizontalOptions="Center"/>\n')
f.write('            <Label Text="Invoices" FontSize="11" TextColor="#7d8590" HorizontalOptions="Center"/>\n')
f.write('          </VerticalStackLayout>\n')
f.write('        </Frame>\n')
f.write('        <Frame Grid.Column="2" BackgroundColor="#161b22" BorderColor="#0ea5e9" CornerRadius="16" Padding="14,12" HasShadow="False">\n')
f.write('          <VerticalStackLayout Spacing="2" HorizontalOptions="Center">\n')
f.write('            <Label Text="{Binding TotalEmployees}" FontSize="26" FontAttributes="Bold" TextColor="#0ea5e9" HorizontalOptions="Center"/>\n')
f.write('            <Label Text="Crew" FontSize="11" TextColor="#7d8590" HorizontalOptions="Center"/>\n')
f.write('          </VerticalStackLayout>\n')
f.write('        </Frame>\n')
f.write('      </Grid>\n')
f.write('      <Label Text="FIELD TOOLS" FontSize="11" TextColor="#3d444d" FontAttributes="Bold" Margin="20,0,0,8"/>\n')
f.write('      <Frame BackgroundColor="#161b22" BorderColor="#21262d" CornerRadius="18" Margin="16,0,16,20" Padding="0" HasShadow="False">\n')
f.write('        <VerticalStackLayout Spacing="0">\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnEmployeesTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#0c1e2e" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F477;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Employees" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="Manage your crew" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('          <BoxView HeightRequest="1" BackgroundColor="#21262d" Margin="16,0"/>\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnMapTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#0d2318" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F5FA;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Job Map" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="View all active job sites" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('          <BoxView HeightRequest="1" BackgroundColor="#21262d" Margin="16,0"/>\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnContractsTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#1e1333" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F4DD;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Contracts" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="Send &amp; sign digitally" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('        </VerticalStackLayout>\n')
f.write('      </Frame>\n')
f.write('      <Label Text="FINANCE" FontSize="11" TextColor="#3d444d" FontAttributes="Bold" Margin="20,0,0,8"/>\n')
f.write('      <Frame BackgroundColor="#161b22" BorderColor="#21262d" CornerRadius="18" Margin="16,0,16,20" Padding="0" HasShadow="False">\n')
f.write('        <VerticalStackLayout Spacing="0">\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnReportsTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#0d2318" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F4CA;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Reports" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="Profit per job &amp; revenue" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('          <BoxView HeightRequest="1" BackgroundColor="#21262d" Margin="16,0"/>\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnEstimatesTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#2a1f00" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F4CB;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Estimates" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="Create &amp; send estimates" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('          <BoxView HeightRequest="1" BackgroundColor="#21262d" Margin="16,0"/>\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnNotificationsTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#0c1e2e" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F514;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Notifications" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="Alerts &amp; updates" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('        </VerticalStackLayout>\n')
f.write('      </Frame>\n')
f.write('      <Label Text="ACCOUNT" FontSize="11" TextColor="#3d444d" FontAttributes="Bold" Margin="20,0,0,8"/>\n')
f.write('      <Frame BackgroundColor="#161b22" BorderColor="#21262d" CornerRadius="18" Margin="16,0,16,20" Padding="0" HasShadow="False">\n')
f.write('        <VerticalStackLayout Spacing="0">\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnSubscriptionTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#2a1f00" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x2B50;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Subscription" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="{Binding PlanName}" FontSize="12" TextColor="#f0a500"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('          <BoxView HeightRequest="1" BackgroundColor="#21262d" Margin="16,0"/>\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnSettingsTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#21262d" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x2699;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Settings" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="App preferences" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('          <BoxView HeightRequest="1" BackgroundColor="#21262d" Margin="16,0"/>\n')
f.write('          <Grid Padding="16,14" ColumnDefinitions="44,*,Auto">\n')
f.write('            <Grid.GestureRecognizers><TapGestureRecognizer Tapped="OnHelpTapped"/></Grid.GestureRecognizers>\n')
f.write('            <Frame Grid.Column="0" BackgroundColor="#0c1e2e" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('              <Label Text="&#x1F4AC;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('            </Frame>\n')
f.write('            <VerticalStackLayout Grid.Column="1" VerticalOptions="Center" Spacing="1">\n')
f.write('              <Label Text="Help &amp; Support" FontSize="15" TextColor="White" FontAttributes="Bold"/>\n')
f.write('              <Label Text="Get help from our team" FontSize="12" TextColor="#7d8590"/>\n')
f.write('            </VerticalStackLayout>\n')
f.write('            <Label Grid.Column="2" Text="&#x203A;" FontSize="22" TextColor="#3d444d" VerticalOptions="Center"/>\n')
f.write('          </Grid>\n')
f.write('        </VerticalStackLayout>\n')
f.write('      </Frame>\n')
f.write('      <Frame BackgroundColor="#1a0f0f" BorderColor="#2d1515" CornerRadius="18" Margin="16,0,16,16" Padding="0" HasShadow="False">\n')
f.write('        <Frame.GestureRecognizers><TapGestureRecognizer Tapped="OnSignOutTapped"/></Frame.GestureRecognizers>\n')
f.write('        <Grid Padding="16,16" ColumnDefinitions="44,*">\n')
f.write('          <Frame Grid.Column="0" BackgroundColor="#2d1515" CornerRadius="10" Padding="0" WidthRequest="36" HeightRequest="36" HasShadow="False" BorderColor="Transparent">\n')
f.write('            <Label Text="&#x1F6AA;" FontSize="18" HorizontalOptions="Center" VerticalOptions="Center"/>\n')
f.write('          </Frame>\n')
f.write('          <Label Grid.Column="1" Text="Sign Out" FontSize="16" FontAttributes="Bold" TextColor="#ef4444" VerticalOptions="Center"/>\n')
f.write('        </Grid>\n')
f.write('      </Frame>\n')
f.write('      <Label Text="BuildForce v1.0 · Mezano Consulting" FontSize="11" TextColor="#3d444d" HorizontalOptions="Center" Margin="0,0,0,32"/>\n')
f.write('    </VerticalStackLayout>\n')
f.write('  </ScrollView>\n')
f.write('</ContentPage>\n')
f.close()
print('Done!')