import os

ROOT  = r"C:\Users\mezan\source\repos\BuildForce\BuildForce"
VIEWS = os.path.join(ROOT, "Views")

def write(path, text):
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))
    print("OK  " + path)

# ═══════════════════════════════════════════════════════════════
# AppShell.xaml — Hide default tab bar (we use floating dock)
# ═══════════════════════════════════════════════════════════════
SHELL = os.path.join(ROOT, "AppShell.xaml")
SHELL_TEXT = (
'<?xml version="1.0" encoding="utf-8" ?>\n'
'<Shell\n'
'    x:Class="BuildForce.AppShell"\n'
'    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"\n'
'    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"\n'
'    xmlns:views="clr-namespace:BuildForce.Views"\n'
'    Shell.NavBarIsVisible="False"\n'
'    Shell.TabBarIsVisible="False">\n'
'    <TabBar>\n'
'        <Tab Title="Dashboard">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:DashboardPage}" Route="DashboardPage"/>\n'
'        </Tab>\n'
'        <Tab Title="Projects">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:ProjectsPage}" Route="ProjectsPage"/>\n'
'        </Tab>\n'
'        <Tab Title="Invoices">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:InvoicesPage}" Route="InvoicesPage"/>\n'
'        </Tab>\n'
'        <Tab Title="Expenses">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:ExpensesPage}" Route="ExpensesPage"/>\n'
'        </Tab>\n'
'        <Tab Title="Time">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:TimesheetPage}" Route="TimesheetPage"/>\n'
'        </Tab>\n'
'        <Tab Title="Customers">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:CustomersPage}" Route="CustomersPage"/>\n'
'        </Tab>\n'
'        <Tab Title="More">\n'
'            <ShellContent ContentTemplate="{DataTemplate views:MorePage}" Route="MorePage"/>\n'
'        </Tab>\n'
'    </TabBar>\n'
'\n'
'    <!-- DETAIL ROUTES -->\n'
'    <Shell.Items>\n'
'        <ShellContent Route="TimesheetDetailPage" ContentTemplate="{DataTemplate views:TimesheetDetailPage}" Shell.TabBarIsVisible="False" Shell.NavBarIsVisible="True"/>\n'
'        <ShellContent Route="ProjectDetailPage" ContentTemplate="{DataTemplate views:ProjectDetailPage}" Shell.TabBarIsVisible="False" Shell.NavBarIsVisible="True"/>\n'
'        <ShellContent Route="InvoiceDetailPage" ContentTemplate="{DataTemplate views:InvoiceDetailPage}" Shell.TabBarIsVisible="False" Shell.NavBarIsVisible="True"/>\n'
'    </Shell.Items>\n'
'</Shell>\n'
)

# ═══════════════════════════════════════════════════════════════
# DashboardPage.xaml — Ultra Modern Bento Dashboard
# ═══════════════════════════════════════════════════════════════
DASH = os.path.join(VIEWS, "DashboardPage.xaml")
DASH_TEXT = (
'<?xml version="1.0" encoding="utf-8" ?>\n'
'<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"\n'
'             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"\n'
'             x:Class="BuildForce.Views.DashboardPage"\n'
'             BackgroundColor="#0e0e0e"\n'
'             Shell.NavBarIsVisible="False"\n'
'             Shell.TabBarIsVisible="False">\n'
'  <Grid RowDefinitions="*,Auto">\n'
'\n'
'    <ScrollView Grid.Row="0">\n'
'      <VerticalStackLayout Spacing="0">\n'
'\n'
'        <!-- HEADER -->\n'
'        <Grid ColumnDefinitions="*,Auto" Padding="20,52,20,16" BackgroundColor="#0e0e0e">\n'
'          <VerticalStackLayout Grid.Column="0" Spacing="2">\n'
'            <Label x:Name="GreetingLabel" Text="Good morning" FontSize="12" TextColor="#888"/>\n'
'            <Label Text="BuildForce" FontSize="28" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'            <Label Text="Mezano Consulting" FontSize="13" TextColor="#555"/>\n'
'          </VerticalStackLayout>\n'
'          <Grid Grid.Column="1" ColumnDefinitions="Auto,Auto" ColumnSpacing="10" VerticalOptions="Center">\n'
'            <!-- Theme toggle pill -->\n'
'            <Border Grid.Column="0" BackgroundColor="#1a1a1a" Stroke="#2a2a2a" StrokeThickness="1" Padding="10,6">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'              <Border.GestureRecognizers>\n'
'                <TapGestureRecognizer Tapped="OnThemeToggleTapped"/>\n'
'              </Border.GestureRecognizers>\n'
'              <Label x:Name="ThemeLabel" Text="Dark" FontSize="11" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'            </Border>\n'
'            <!-- Avatar -->\n'
'            <Border Grid.Column="1" BackgroundColor="#1a1a1a" Stroke="#f0a500" StrokeThickness="1" WidthRequest="44" HeightRequest="44">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="14"/></Border.StrokeShape>\n'
'              <Label Text="MC" FontSize="13" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="Center" VerticalOptions="Center"/>\n'
'            </Border>\n'
'          </Grid>\n'
'        </Grid>\n'
'\n'
'        <!-- PLAN BADGE -->\n'
'        <Border Margin="20,0,20,16" BackgroundColor="#1a1200" Stroke="#f0a500" StrokeThickness="0.5" Padding="12,7">\n'
'          <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'          <HorizontalStackLayout Spacing="8">\n'
'            <Label Text="PRO BUILDER" FontSize="11" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'            <Label Text="·" FontSize="11" TextColor="#555"/>\n'
'            <Label Text="Mezano Consulting LLC" FontSize="11" TextColor="#666"/>\n'
'          </HorizontalStackLayout>\n'
'        </Border>\n'
'\n'
'        <!-- BENTO BUDGET CARD -->\n'
'        <Border Margin="20,0,20,12" BackgroundColor="#1a1400" Stroke="#f0a500" StrokeThickness="1.5" Padding="20,18">\n'
'          <Border.StrokeShape><RoundRectangle CornerRadius="24"/></Border.StrokeShape>\n'
'          <VerticalStackLayout Spacing="10">\n'
'            <Label Text="INVOICES OVERVIEW" FontSize="9" FontAttributes="Bold" TextColor="#555" CharacterSpacing="2"/>\n'
'            <Grid ColumnDefinitions="*,Auto">\n'
'              <VerticalStackLayout Grid.Column="0" Spacing="2">\n'
'                <Label Text="Unpaid" FontSize="12" TextColor="#888"/>\n'
'                <Label x:Name="UnpaidAmountLabel" Text="$0.00" FontSize="36" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'              </VerticalStackLayout>\n'
'              <Border Grid.Column="1" BackgroundColor="#2a1800" Stroke="#f0a500" StrokeThickness="0.5" Padding="10,6" VerticalOptions="Center">\n'
'                <Border.StrokeShape><RoundRectangle CornerRadius="10"/></Border.StrokeShape>\n'
'                <Label x:Name="OverdueCountLabel" Text="0 Overdue" FontSize="11" TextColor="#f0a500" FontAttributes="Bold"/>\n'
'              </Border>\n'
'            </Grid>\n'
'            <!-- Progress bar -->\n'
'            <Border BackgroundColor="#2a2a2a" HeightRequest="6">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="4"/></Border.StrokeShape>\n'
'              <BoxView x:Name="PaidProgressBar" BackgroundColor="#22c55e" HeightRequest="6" HorizontalOptions="Start" WidthRequest="0"/>\n'
'            </Border>\n'
'            <Grid ColumnDefinitions="Auto,*,Auto">\n'
'              <Label Grid.Column="0" Text="Overdue" FontSize="10" TextColor="#f0a500"/>\n'
'              <Label Grid.Column="2" Text="Paid" FontSize="10" TextColor="#22c55e"/>\n'
'            </Grid>\n'
'            <BoxView HeightRequest="1" BackgroundColor="#2a2a2a"/>\n'
'            <Grid ColumnDefinitions="*,*" ColumnSpacing="10">\n'
'              <VerticalStackLayout Grid.Column="0" Spacing="2">\n'
'                <Label Text="Paid" FontSize="11" TextColor="#888"/>\n'
'                <Label x:Name="PaidAmountLabel" Text="$0.00" FontSize="22" FontAttributes="Bold" TextColor="#22c55e"/>\n'
'              </VerticalStackLayout>\n'
'              <VerticalStackLayout Grid.Column="1" Spacing="2">\n'
'                <Label Text="Total Outstanding" FontSize="11" TextColor="#888"/>\n'
'                <Label x:Name="TotalOutstandingLabel" Text="$0.00" FontSize="22" FontAttributes="Bold" TextColor="#ffffff"/>\n'
'              </VerticalStackLayout>\n'
'            </Grid>\n'
'          </VerticalStackLayout>\n'
'        </Border>\n'
'\n'
'        <!-- BENTO STATS ROW -->\n'
'        <Grid Margin="20,0,20,12" ColumnDefinitions="*,*,*" ColumnSpacing="10">\n'
'          <Border Grid.Column="0" BackgroundColor="#0c1e2e" Stroke="#0ea5e9" StrokeThickness="0.5" Padding="14,12">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="4">\n'
'              <Label Text="ACTIVE" FontSize="8" FontAttributes="Bold" TextColor="#0ea5e9" CharacterSpacing="1"/>\n'
'              <Label x:Name="ActiveJobsLabel" Text="0" FontSize="28" FontAttributes="Bold" TextColor="#0ea5e9" HorizontalOptions="Center"/>\n'
'              <Label Text="Jobs" FontSize="10" TextColor="#555" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Column="1" BackgroundColor="#1a0a0a" Stroke="#ef4444" StrokeThickness="0.5" Padding="14,12">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="4">\n'
'              <Label Text="URGENT" FontSize="8" FontAttributes="Bold" TextColor="#ef4444" CharacterSpacing="1"/>\n'
'              <Label x:Name="NeedsAttentionLabel" Text="0" FontSize="28" FontAttributes="Bold" TextColor="#ef4444" HorizontalOptions="Center"/>\n'
'              <Label Text="Attention" FontSize="10" TextColor="#555" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Column="2" BackgroundColor="#160a28" Stroke="#8b5cf6" StrokeThickness="0.5" Padding="14,12">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="4">\n'
'              <Label Text="PENDING" FontSize="8" FontAttributes="Bold" TextColor="#8b5cf6" CharacterSpacing="1"/>\n'
'              <Label x:Name="EstimatesLabel" Text="0" FontSize="28" FontAttributes="Bold" TextColor="#8b5cf6" HorizontalOptions="Center"/>\n'
'              <Label Text="Estimates" FontSize="10" TextColor="#555" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'        </Grid>\n'
'\n'
'        <!-- QUICK ACTIONS -->\n'
'        <Label Text="QUICK ACTIONS" Margin="20,8,20,10" FontSize="10" FontAttributes="Bold" TextColor="#444" CharacterSpacing="2"/>\n'
'\n'
'        <Grid Margin="20,0,20,12" ColumnDefinitions="*,*" RowDefinitions="Auto,Auto" ColumnSpacing="10" RowSpacing="10">\n'
'          <Border Grid.Row="0" Grid.Column="0" BackgroundColor="#161616" Stroke="#2a2a2a" StrokeThickness="1" Padding="16,14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'            <Border.GestureRecognizers><TapGestureRecognizer Tapped="OnNewInvoiceTapped"/></Border.GestureRecognizers>\n'
'            <VerticalStackLayout Spacing="8">\n'
'              <Label Text="🧾" FontSize="26"/>\n'
'              <Label Text="New Invoice" FontSize="14" FontAttributes="Bold" TextColor="#ffffff"/>\n'
'              <Label Text="60 seconds" FontSize="11" TextColor="#555"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Row="0" Grid.Column="1" BackgroundColor="#161616" Stroke="#2a2a2a" StrokeThickness="1" Padding="16,14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'            <Border.GestureRecognizers><TapGestureRecognizer Tapped="OnScanReceiptTapped"/></Border.GestureRecognizers>\n'
'            <VerticalStackLayout Spacing="8">\n'
'              <Label Text="📷" FontSize="26"/>\n'
'              <Label Text="Scan Receipt" FontSize="14" FontAttributes="Bold" TextColor="#ffffff"/>\n'
'              <Label Text="AI auto-fill" FontSize="11" TextColor="#555"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Row="1" Grid.Column="0" BackgroundColor="#080d08" Stroke="#22c55e" StrokeThickness="1" Padding="16,14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'            <Border.GestureRecognizers><TapGestureRecognizer Tapped="OnTimeClockTapped"/></Border.GestureRecognizers>\n'
'            <VerticalStackLayout Spacing="8">\n'
'              <Label Text="⏱️" FontSize="26"/>\n'
'              <Label Text="Time Clock" FontSize="14" FontAttributes="Bold" TextColor="#22c55e"/>\n'
'              <Label Text="GPS verified" FontSize="11" TextColor="#555"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Row="1" Grid.Column="1" BackgroundColor="#1a1200" Stroke="#f0a500" StrokeThickness="1" Padding="16,14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'            <Border.GestureRecognizers><TapGestureRecognizer Tapped="OnCollectPayTapped"/></Border.GestureRecognizers>\n'
'            <VerticalStackLayout Spacing="8">\n'
'              <Label Text="💳" FontSize="26"/>\n'
'              <Label Text="Collect Pay" FontSize="14" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'              <Label Text="On-site payment" FontSize="11" TextColor="#555"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'        </Grid>\n'
'\n'
'        <!-- ACTIVE JOBS -->\n'
'        <Grid Margin="20,0,20,10" ColumnDefinitions="*,Auto">\n'
'          <Label Grid.Column="0" Text="ACTIVE JOBS" FontSize="10" FontAttributes="Bold" TextColor="#444" CharacterSpacing="2"/>\n'
'          <Label Grid.Column="1" Text="See all" FontSize="12" TextColor="#f0a500">\n'
'            <Label.GestureRecognizers><TapGestureRecognizer Tapped="OnSeeAllProjectsTapped"/></Label.GestureRecognizers>\n'
'          </Label>\n'
'        </Grid>\n'
'\n'
'        <CollectionView x:Name="ActiveJobsCollection" Margin="20,0,20,0" SelectionMode="None">\n'
'          <CollectionView.ItemTemplate>\n'
'            <DataTemplate>\n'
'              <Border BackgroundColor="#161616" Stroke="#2a2a2a" StrokeThickness="1" Padding="16" Margin="0,0,0,10">\n'
'                <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'                <Grid ColumnDefinitions="Auto,*,Auto" ColumnSpacing="12">\n'
'                  <!-- Color accent bar -->\n'
'                  <BoxView Grid.Column="0" BackgroundColor="#f0a500" WidthRequest="3" CornerRadius="2" VerticalOptions="Fill"/>\n'
'                  <VerticalStackLayout Grid.Column="1" Spacing="3">\n'
'                    <Label Text="{Binding Name}" FontSize="15" FontAttributes="Bold" TextColor="#ffffff"/>\n'
'                    <Label Text="{Binding CustomerName}" FontSize="12" TextColor="#666"/>\n'
'                  </VerticalStackLayout>\n'
'                  <VerticalStackLayout Grid.Column="2" HorizontalOptions="End" Spacing="4">\n'
'                    <Label Text="{Binding BudgetFormatted}" FontSize="15" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="End"/>\n'
'                    <Border BackgroundColor="#1a1200" Padding="8,3">\n'
'                      <Border.StrokeShape><RoundRectangle CornerRadius="8"/></Border.StrokeShape>\n'
'                      <Label Text="{Binding Status}" FontSize="10" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'                    </Border>\n'
'                  </VerticalStackLayout>\n'
'                </Grid>\n'
'              </Border>\n'
'            </DataTemplate>\n'
'          </CollectionView.ItemTemplate>\n'
'        </CollectionView>\n'
'\n'
'        <ActivityIndicator x:Name="LoadingIndicator" IsRunning="False" IsVisible="False" Color="#f0a500" HorizontalOptions="Center" Margin="0,10,0,0"/>\n'
'\n'
'        <BoxView HeightRequest="100" Color="Transparent"/>\n'
'      </VerticalStackLayout>\n'
'    </ScrollView>\n'
'\n'
'    <!-- FLOATING DOCK -->\n'
'    <Grid Grid.Row="0" VerticalOptions="End" Margin="16,0,16,28" ZIndex="100">\n'
'      <Border BackgroundColor="#161616" Stroke="#2a2a2a" StrokeThickness="1" Padding="12,10">\n'
'        <Border.StrokeShape><RoundRectangle CornerRadius="28"/></Border.StrokeShape>\n'
'        <Grid ColumnDefinitions="*,*,Auto,*,*" ColumnSpacing="0">\n'
'\n'
'          <!-- Dashboard -->\n'
'          <VerticalStackLayout Grid.Column="0" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <Border BackgroundColor="#1a1200" Padding="6,4" HorizontalOptions="Center">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="10"/></Border.StrokeShape>\n'
'              <Label Text="⊞" FontSize="20" TextColor="#f0a500" HorizontalOptions="Center"/>\n'
'            </Border>\n'
'            <Label Text="DASH" FontSize="8" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'\n'
'          <!-- Projects -->\n'
'          <VerticalStackLayout Grid.Column="1" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers>\n'
'              <TapGestureRecognizer Tapped="OnDockProjectsTapped"/>\n'
'            </VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="📁" FontSize="20" HorizontalOptions="Center"/>\n'
'            <Label Text="JOBS" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'\n'
'          <!-- CENTER TIME CLOCK -->\n'
'          <Border Grid.Column="2" BackgroundColor="#f0a500" WidthRequest="56" HeightRequest="56" Margin="0,-10,0,0" VerticalOptions="End">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'            <Border.GestureRecognizers>\n'
'              <TapGestureRecognizer Tapped="OnTimeClockTapped"/>\n'
'            </Border.GestureRecognizers>\n'
'            <Label Text="⏱" FontSize="24" HorizontalOptions="Center" VerticalOptions="Center"/>\n'
'          </Border>\n'
'\n'
'          <!-- Invoices -->\n'
'          <VerticalStackLayout Grid.Column="3" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers>\n'
'              <TapGestureRecognizer Tapped="OnDockInvoicesTapped"/>\n'
'            </VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="📄" FontSize="20" HorizontalOptions="Center"/>\n'
'            <Label Text="PAY" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'\n'
'          <!-- More -->\n'
'          <VerticalStackLayout Grid.Column="4" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers>\n'
'              <TapGestureRecognizer Tapped="OnDockMoreTapped"/>\n'
'            </VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="⋯" FontSize="20" HorizontalOptions="Center" TextColor="#666"/>\n'
'            <Label Text="MORE" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'\n'
'        </Grid>\n'
'      </Border>\n'
'    </Grid>\n'
'\n'
'  </Grid>\n'
'</ContentPage>\n'
)

# ═══════════════════════════════════════════════════════════════
# TimesheetPage.xaml — Ultra Modern Time Clock
# ═══════════════════════════════════════════════════════════════
TS = os.path.join(VIEWS, "TimesheetPage.xaml")
TS_TEXT = (
'<?xml version="1.0" encoding="utf-8" ?>\n'
'<ContentPage\n'
'    x:Class="BuildForce.Views.TimesheetPage"\n'
'    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"\n'
'    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"\n'
'    Title="Time Clock"\n'
'    BackgroundColor="#0e0e0e"\n'
'    Shell.NavBarIsVisible="False"\n'
'    Shell.TabBarIsVisible="False">\n'
'  <Grid RowDefinitions="*,Auto">\n'
'\n'
'    <RefreshView Grid.Row="0" Command="{Binding RefreshCommand}" IsRefreshing="{Binding IsBusy}" RefreshColor="#f0a500">\n'
'      <ScrollView>\n'
'        <VerticalStackLayout Padding="20,52,20,16" Spacing="16">\n'
'\n'
'          <!-- HEADER -->\n'
'          <Grid ColumnDefinitions="*,Auto">\n'
'            <VerticalStackLayout Grid.Column="0" Spacing="2">\n'
'              <Label Text="TIME CLOCK" FontSize="28" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'              <Label Text="Phoenix, AZ · GPS Active" FontSize="12" TextColor="#555"/>\n'
'            </VerticalStackLayout>\n'
'            <Border Grid.Column="1" BackgroundColor="#1a1a1a" Stroke="#2a2a2a" StrokeThickness="1" WidthRequest="44" HeightRequest="44" VerticalOptions="Center">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="14"/></Border.StrokeShape>\n'
'              <Label Text="CM" FontSize="13" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="Center" VerticalOptions="Center"/>\n'
'            </Border>\n'
'          </Grid>\n'
'\n'
'          <!-- CLOCK HERO CARD -->\n'
'          <Border BackgroundColor="#0d0b05" Stroke="#f0a500" StrokeThickness="1.5" Padding="24,22">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="28"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="16">\n'
'\n'
'              <Label Text="TIME CLOCK" FontSize="10" FontAttributes="Bold" TextColor="#f0a500" CharacterSpacing="2" HorizontalOptions="Center"/>\n'
'\n'
'              <!-- Timer -->\n'
'              <Label Text="{Binding ClockDuration}" FontSize="60" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="Center" IsVisible="{Binding IsClockedIn}" CharacterSpacing="-2"/>\n'
'              <Label Text="00:00:00" FontSize="60" FontAttributes="Bold" TextColor="#1a1800" HorizontalOptions="Center" IsVisible="{Binding IsNotClockedIn}" CharacterSpacing="-2"/>\n'
'\n'
'              <!-- Project picker -->\n'
'              <VerticalStackLayout Spacing="8" IsVisible="{Binding IsNotClockedIn}">\n'
'                <Label Text="SELECT PROJECT" FontSize="9" FontAttributes="Bold" TextColor="#f0a500" CharacterSpacing="2"/>\n'
'                <Border BackgroundColor="#0a0800" Stroke="#f0a500" StrokeThickness="0.5" Padding="16,12">\n'
'                  <Border.StrokeShape><RoundRectangle CornerRadius="14"/></Border.StrokeShape>\n'
'                  <Picker ItemsSource="{Binding Projects}" SelectedItem="{Binding SelectedProject}" ItemDisplayBinding="{Binding Name}" TextColor="#ffffff" TitleColor="#444" Title="Choose a project..." BackgroundColor="Transparent"/>\n'
'                </Border>\n'
'              </VerticalStackLayout>\n'
'\n'
'              <!-- Active project + cost code pill -->\n'
'              <VerticalStackLayout Spacing="8" IsVisible="{Binding IsClockedIn}">\n'
'                <Label Text="WORKING ON" FontSize="9" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="2"/>\n'
'                <Label Text="{Binding SelectedProject.Name}" FontSize="18" FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'                <Label Text="{Binding CurrentEmployeeName}" FontSize="12" TextColor="#888" HorizontalOptions="Center"/>\n'
'                <!-- Cost code pill -->\n'
'                <Border BackgroundColor="#1a1200" Stroke="#f0a500" StrokeThickness="0.5" Padding="14,8" HorizontalOptions="Center">\n'
'                  <Border.StrokeShape><RoundRectangle CornerRadius="12"/></Border.StrokeShape>\n'
'                  <HorizontalStackLayout Spacing="8">\n'
'                    <BoxView WidthRequest="6" HeightRequest="6" CornerRadius="3" BackgroundColor="#f0a500" VerticalOptions="Center"/>\n'
'                    <Label Text="06-100 · Framing" FontSize="12" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'                  </HorizontalStackLayout>\n'
'                </Border>\n'
'              </VerticalStackLayout>\n'
'\n'
'              <!-- GPS badge -->\n'
'              <Border BackgroundColor="#080d08" Stroke="#22c55e" StrokeThickness="0.5" Padding="12,7" HorizontalOptions="Center">\n'
'                <Border.StrokeShape><RoundRectangle CornerRadius="12"/></Border.StrokeShape>\n'
'                <HorizontalStackLayout Spacing="6">\n'
'                  <Label Text="📍" FontSize="12"/>\n'
'                  <Label Text="On Site · GPS Verified" FontSize="11" TextColor="#22c55e" FontAttributes="Bold"/>\n'
'                </HorizontalStackLayout>\n'
'              </Border>\n'
'\n'
'              <!-- Clock button -->\n'
'              <Button Text="{Binding ClockButtonText}" Command="{Binding ClockToggleCommand}" BackgroundColor="{Binding ClockButtonColor}" TextColor="#ffffff" FontAttributes="Bold" FontSize="18" CornerRadius="18" HeightRequest="62" Margin="0,4,0,0"/>\n'
'\n'
'              <Label Text="{Binding ErrorMessage}" FontSize="13" TextColor="#ef4444" HorizontalOptions="Center" IsVisible="{Binding HasError}" HorizontalTextAlignment="Center"/>\n'
'\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'\n'
'          <!-- WEEKLY STATS -->\n'
'          <Label Text="THIS WEEK" FontSize="10" FontAttributes="Bold" TextColor="#444" CharacterSpacing="2"/>\n'
'\n'
'          <Grid ColumnDefinitions="*,*,*" ColumnSpacing="10">\n'
'            <Border Grid.Column="0" BackgroundColor="#0d0b05" Stroke="#f0a500" StrokeThickness="0.5" Padding="14">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'              <VerticalStackLayout Spacing="4" HorizontalOptions="Center">\n'
'                <Label Text="REGULAR" FontSize="8" FontAttributes="Bold" TextColor="#f0a500" CharacterSpacing="1" HorizontalOptions="Center"/>\n'
'                <Label Text="{Binding WeeklySummary.TotalRegularHours, StringFormat=\'{0:F1}h\'}" FontSize="26" FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'              </VerticalStackLayout>\n'
'            </Border>\n'
'            <Border Grid.Column="1" BackgroundColor="#0d0808" Stroke="#ef4444" StrokeThickness="0.5" Padding="14">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'              <VerticalStackLayout Spacing="4" HorizontalOptions="Center">\n'
'                <Label Text="OVERTIME" FontSize="8" FontAttributes="Bold" TextColor="#ef4444" CharacterSpacing="1" HorizontalOptions="Center"/>\n'
'                <Label Text="{Binding WeeklySummary.TotalOvertimeHours, StringFormat=\'{0:F1}h\'}" FontSize="26" FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'              </VerticalStackLayout>\n'
'            </Border>\n'
'            <Border Grid.Column="2" BackgroundColor="#080d08" Stroke="#22c55e" StrokeThickness="0.5" Padding="14">\n'
'              <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'              <VerticalStackLayout Spacing="4" HorizontalOptions="Center">\n'
'                <Label Text="TOTAL" FontSize="8" FontAttributes="Bold" TextColor="#22c55e" CharacterSpacing="1" HorizontalOptions="Center"/>\n'
'                <Label Text="{Binding WeeklySummary.TotalHours, StringFormat=\'{0:F1}h\'}" FontSize="26" FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'              </VerticalStackLayout>\n'
'            </Border>\n'
'          </Grid>\n'
'\n'
'          <!-- RECENT ENTRIES -->\n'
'          <Label Text="RECENT ENTRIES" FontSize="10" FontAttributes="Bold" TextColor="#444" CharacterSpacing="2"/>\n'
'\n'
'          <CollectionView x:Name="TimesheetList" ItemsSource="{Binding Timesheets}" SelectionMode="Single" SelectionChanged="TimesheetList_SelectionChanged">\n'
'            <CollectionView.ItemTemplate>\n'
'              <DataTemplate>\n'
'                <Border BackgroundColor="#161616" Stroke="#2a2a2a" StrokeThickness="1" Padding="16,14" Margin="0,0,0,10">\n'
'                  <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'                  <Grid ColumnDefinitions="Auto,*,Auto" ColumnSpacing="12">\n'
'                    <!-- Accent bar -->\n'
'                    <BoxView Grid.Column="0" BackgroundColor="#f0a500" WidthRequest="3" CornerRadius="2" VerticalOptions="Fill"/>\n'
'                    <VerticalStackLayout Grid.Column="1" Spacing="4">\n'
'                      <Label Text="{Binding ProjectName}" FontAttributes="Bold" FontSize="15" TextColor="#ffffff"/>\n'
'                      <HorizontalStackLayout Spacing="8">\n'
'                        <!-- Cost code pill -->\n'
'                        <Border BackgroundColor="#1a1200" Padding="6,3">\n'
'                          <Border.StrokeShape><RoundRectangle CornerRadius="6"/></Border.StrokeShape>\n'
'                          <Label Text="06-100" FontSize="10" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'                        </Border>\n'
'                        <Label Text="{Binding Date, StringFormat=\'{0:MMM d, yyyy}\'}" FontSize="11" TextColor="#555" VerticalOptions="Center"/>\n'
'                      </HorizontalStackLayout>\n'
'                      <Label Text="{Binding EmployeeName}" FontSize="11" TextColor="#555"/>\n'
'                    </VerticalStackLayout>\n'
'                    <VerticalStackLayout Grid.Column="2" HorizontalOptions="End" Spacing="6">\n'
'                      <Label Text="{Binding HoursWorked, StringFormat=\'{0:F1}h\'}" FontAttributes="Bold" FontSize="20" TextColor="#f0a500" HorizontalOptions="End"/>\n'
'                      <Label Text="{Binding Status}" FontSize="10" TextColor="#555" HorizontalOptions="End"/>\n'
'                      <Label Text=">" FontSize="14" TextColor="#333" HorizontalOptions="End"/>\n'
'                    </VerticalStackLayout>\n'
'                  </Grid>\n'
'                </Border>\n'
'              </DataTemplate>\n'
'            </CollectionView.ItemTemplate>\n'
'          </CollectionView>\n'
'\n'
'          <BoxView HeightRequest="100" Color="Transparent"/>\n'
'        </VerticalStackLayout>\n'
'      </ScrollView>\n'
'    </RefreshView>\n'
'\n'
'    <!-- FLOATING DOCK -->\n'
'    <Grid Grid.Row="0" VerticalOptions="End" Margin="16,0,16,28" ZIndex="100">\n'
'      <Border BackgroundColor="#161616" Stroke="#2a2a2a" StrokeThickness="1" Padding="12,10">\n'
'        <Border.StrokeShape><RoundRectangle CornerRadius="28"/></Border.StrokeShape>\n'
'        <Grid ColumnDefinitions="*,*,Auto,*,*" ColumnSpacing="0">\n'
'          <VerticalStackLayout Grid.Column="0" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers><TapGestureRecognizer Tapped="OnDockDashTapped"/></VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="⊞" FontSize="20" HorizontalOptions="Center" TextColor="#666"/>\n'
'            <Label Text="DASH" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'          <VerticalStackLayout Grid.Column="1" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers><TapGestureRecognizer Tapped="OnDockProjectsTapped"/></VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="📁" FontSize="20" HorizontalOptions="Center"/>\n'
'            <Label Text="JOBS" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'          <!-- CENTER ACTIVE -->\n'
'          <Border Grid.Column="2" BackgroundColor="#f0a500" WidthRequest="56" HeightRequest="56" Margin="0,-10,0,0" VerticalOptions="End">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="18"/></Border.StrokeShape>\n'
'            <Label Text="⏱" FontSize="24" HorizontalOptions="Center" VerticalOptions="Center"/>\n'
'          </Border>\n'
'          <VerticalStackLayout Grid.Column="3" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers><TapGestureRecognizer Tapped="OnDockInvoicesTapped"/></VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="📄" FontSize="20" HorizontalOptions="Center"/>\n'
'            <Label Text="PAY" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'          <VerticalStackLayout Grid.Column="4" Spacing="3" HorizontalOptions="Center" Padding="8,4">\n'
'            <VerticalStackLayout.GestureRecognizers><TapGestureRecognizer Tapped="OnDockMoreTapped"/></VerticalStackLayout.GestureRecognizers>\n'
'            <Label Text="⋯" FontSize="20" HorizontalOptions="Center" TextColor="#666"/>\n'
'            <Label Text="MORE" FontSize="8" FontAttributes="Bold" TextColor="#444" HorizontalOptions="Center" CharacterSpacing="0.5"/>\n'
'          </VerticalStackLayout>\n'
'        </Grid>\n'
'      </Border>\n'
'    </Grid>\n'
'\n'
'  </Grid>\n'
'</ContentPage>\n'
)

# Write all files
write(SHELL, SHELL_TEXT)
write(DASH,  DASH_TEXT)
write(TS,    TS_TEXT)

print("\nAll done! Now update DashboardPage.xaml.cs and TimesheetPage.xaml.cs with dock handlers.")
print("Build and deploy to Samsung.")

# ═══════════════════════════════════════════════════════════════
# DashboardPage.xaml.cs — with dock handlers + theme toggle
# ═══════════════════════════════════════════════════════════════
DASH_CS = os.path.join(VIEWS, "DashboardPage.xaml.cs")
DASH_CS_TEXT = (
'#pragma warning disable CA1416\n'
'using BuildForce.ViewModels;\n'
'\n'
'namespace BuildForce.Views;\n'
'\n'
'public partial class DashboardPage : ContentPage\n'
'{\n'
'    readonly DashboardViewModel _vm;\n'
'    int _themeIndex = 0;\n'
'    readonly string[] _themes = { "Dark", "Navy", "Light" };\n'
'    readonly string[] _bgColors = { "#0e0e0e", "#0a1628", "#f0f2f5" };\n'
'    readonly string[] _surfaceColors = { "#161616", "#0f2040", "#ffffff" };\n'
'\n'
'    public DashboardPage(DashboardViewModel vm)\n'
'    {\n'
'        InitializeComponent();\n'
'        _vm = vm;\n'
'        BindingContext = vm;\n'
'        UpdateGreeting();\n'
'    }\n'
'\n'
'    protected override async void OnAppearing()\n'
'    {\n'
'        base.OnAppearing();\n'
'        await _vm.LoadAsync();\n'
'        UpdateGreeting();\n'
'    }\n'
'\n'
'    void UpdateGreeting()\n'
'    {\n'
'        var hour = DateTime.Now.Hour;\n'
'        GreetingLabel.Text = hour < 12 ? "Good morning" : hour < 17 ? "Good afternoon" : "Good evening";\n'
'    }\n'
'\n'
'    void OnThemeToggleTapped(object sender, EventArgs e)\n'
'    {\n'
'        _themeIndex = (_themeIndex + 1) % _themes.Length;\n'
'        ThemeLabel.Text = _themes[_themeIndex];\n'
'        var bg = Color.FromArgb(_bgColors[_themeIndex]);\n'
'        BackgroundColor = bg;\n'
'        // In a full implementation this would update AppShell resources\n'
'    }\n'
'\n'
'    // QUICK ACTIONS\n'
'    async void OnNewInvoiceTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("CreateInvoicePage");\n'
'\n'
'    async void OnScanReceiptTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.DisplayAlert("Scan Receipt", "AI receipt scanning coming soon!", "OK");\n'
'\n'
'    async void OnTimeClockTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//TimesheetPage");\n'
'\n'
'    async void OnCollectPayTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.DisplayAlert("Collect Payment", "Select an invoice to collect payment.", "OK");\n'
'\n'
'    async void OnSeeAllProjectsTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//ProjectsPage");\n'
'\n'
'    // FLOATING DOCK\n'
'    async void OnDockProjectsTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//ProjectsPage");\n'
'\n'
'    async void OnDockInvoicesTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//InvoicesPage");\n'
'\n'
'    async void OnDockMoreTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//MorePage");\n'
'}\n'
)

# ═══════════════════════════════════════════════════════════════
# TimesheetPage.xaml.cs — with dock handlers
# ═══════════════════════════════════════════════════════════════
TS_CS = os.path.join(VIEWS, "TimesheetPage.xaml.cs")
TS_CS_TEXT = (
'#pragma warning disable CA1416\n'
'using BuildForce.Models;\n'
'using BuildForce.ViewModels;\n'
'\n'
'namespace BuildForce.Views;\n'
'\n'
'public partial class TimesheetPage : ContentPage\n'
'{\n'
'    readonly TimesheetViewModel _vm;\n'
'\n'
'    public TimesheetPage(TimesheetViewModel vm)\n'
'    {\n'
'        InitializeComponent();\n'
'        _vm = vm;\n'
'        BindingContext = vm;\n'
'    }\n'
'\n'
'    protected override async void OnAppearing()\n'
'    {\n'
'        base.OnAppearing();\n'
'        await _vm.LoadAsync();\n'
'    }\n'
'\n'
'    private async void TimesheetList_SelectionChanged(object sender, SelectionChangedEventArgs e)\n'
'    {\n'
'        if (e.CurrentSelection.FirstOrDefault() is not TimesheetDto selected)\n'
'            return;\n'
'        ((CollectionView)sender).SelectedItem = null;\n'
'        await Shell.Current.GoToAsync($"TimesheetDetailPage?timesheetId={selected.TimesheetId}");\n'
'    }\n'
'\n'
'    // FLOATING DOCK\n'
'    async void OnDockDashTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//DashboardPage");\n'
'\n'
'    async void OnDockProjectsTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//ProjectsPage");\n'
'\n'
'    async void OnDockInvoicesTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//InvoicesPage");\n'
'\n'
'    async void OnDockMoreTapped(object sender, EventArgs e)\n'
'        => await Shell.Current.GoToAsync("//MorePage");\n'
'}\n'
)

write(DASH_CS, DASH_CS_TEXT)
write(TS_CS,   TS_CS_TEXT)

print("\nAll 5 files written successfully!")
print("Run: python fix_ultramodern.py")