import os

ROOT  = r"C:\Users\mezan\source\repos\BuildForce\BuildForce"
VIEWS = os.path.join(ROOT, "Views")

def write(path, text):
    with open(path, "wb") as f:
        f.write(text.encode("utf-8"))
    print("OK  " + path)

# ─────────────────────────────────────────────────────────────────────────────
# TimesheetPage.xaml
# ─────────────────────────────────────────────────────────────────────────────
TS_XAML = os.path.join(VIEWS, "TimesheetPage.xaml")
TS_XAML_TEXT = (
'<?xml version="1.0" encoding="utf-8" ?>\n'
'<ContentPage\n'
'    x:Class="BuildForce.Views.TimesheetPage"\n'
'    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"\n'
'    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"\n'
'    Title="Time Clock"\n'
'    BackgroundColor="#080806">\n'
'  <RefreshView Command="{Binding RefreshCommand}" IsRefreshing="{Binding IsBusy}" RefreshColor="#f0a500">\n'
'    <ScrollView>\n'
'      <VerticalStackLayout Padding="20,16" Spacing="20">\n'
'\n'
'        <!-- CLOCK CARD -->\n'
'        <Border BackgroundColor="#0d0b05" Stroke="#f0a500" StrokeThickness="1.5" Padding="24,28">\n'
'          <Border.StrokeShape><RoundRectangle CornerRadius="24"/></Border.StrokeShape>\n'
'          <VerticalStackLayout Spacing="20">\n'
'\n'
'            <Label Text="TIME CLOCK" FontSize="11" FontAttributes="Bold" TextColor="#f0a500"\n'
'                   HorizontalOptions="Center"/>\n'
'\n'
'            <Label Text="{Binding ClockDuration}" FontSize="56" FontAttributes="Bold"\n'
'                   TextColor="#f0a500" HorizontalOptions="Center"\n'
'                   IsVisible="{Binding IsClockedIn}"/>\n'
'\n'
'            <Label Text="00:00:00" FontSize="56" FontAttributes="Bold"\n'
'                   TextColor="#1a1800" HorizontalOptions="Center"\n'
'                   IsVisible="{Binding IsNotClockedIn}"/>\n'
'\n'
'            <VerticalStackLayout Spacing="8" IsVisible="{Binding IsNotClockedIn}">\n'
'              <Label Text="SELECT PROJECT" FontSize="10" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'              <Border BackgroundColor="#0a0800" Stroke="#f0a500" StrokeThickness="0.5" Padding="16,12">\n'
'                <Border.StrokeShape><RoundRectangle CornerRadius="12"/></Border.StrokeShape>\n'
'                <Picker ItemsSource="{Binding Projects}" SelectedItem="{Binding SelectedProject}"\n'
'                        ItemDisplayBinding="{Binding Name}" TextColor="#ffffff"\n'
'                        TitleColor="#555" Title="Choose a project..."\n'
'                        BackgroundColor="Transparent"/>\n'
'              </Border>\n'
'            </VerticalStackLayout>\n'
'\n'
'            <VerticalStackLayout Spacing="6" IsVisible="{Binding IsClockedIn}" HorizontalOptions="Center">\n'
'              <Label Text="WORKING ON" FontSize="10" TextColor="#555" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding SelectedProject.Name}" FontSize="20" FontAttributes="Bold"\n'
'                     TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding CurrentEmployeeName}" FontSize="13" TextColor="#888"\n'
'                     HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'\n'
'            <Button Text="{Binding ClockButtonText}"\n'
'                    Command="{Binding ClockToggleCommand}"\n'
'                    BackgroundColor="{Binding ClockButtonColor}"\n'
'                    TextColor="#ffffff" FontAttributes="Bold" FontSize="20"\n'
'                    CornerRadius="18" HeightRequest="72"\n'
'                    Margin="0,4,0,0"/>\n'
'\n'
'            <Label Text="GPS location will be recorded" FontSize="11" TextColor="#333"\n'
'                   HorizontalOptions="Center"/>\n'
'\n'
'            <Label Text="{Binding ErrorMessage}" FontSize="13" TextColor="#ef4444"\n'
'                   HorizontalOptions="Center" IsVisible="{Binding HasError}"\n'
'                   HorizontalTextAlignment="Center"/>\n'
'\n'
'          </VerticalStackLayout>\n'
'        </Border>\n'
'\n'
'        <Label Text="THIS WEEK" FontSize="11" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'\n'
'        <Grid ColumnDefinitions="*,*,*" ColumnSpacing="10">\n'
'          <Border Grid.Column="0" BackgroundColor="#0d0b05" Stroke="#f0a500" StrokeThickness="0.5" Padding="14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="14"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="4" HorizontalOptions="Center">\n'
'              <Label Text="REGULAR" FontSize="9" FontAttributes="Bold" TextColor="#f0a500" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding WeeklySummary.TotalRegularHours, StringFormat={}{0:F1}h}" FontSize="24"\n'
'                     FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Column="1" BackgroundColor="#0d0808" Stroke="#ef4444" StrokeThickness="0.5" Padding="14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="14"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="4" HorizontalOptions="Center">\n'
'              <Label Text="OVERTIME" FontSize="9" FontAttributes="Bold" TextColor="#ef4444" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding WeeklySummary.TotalOvertimeHours, StringFormat={}{0:F1}h}" FontSize="24"\n'
'                     FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'          <Border Grid.Column="2" BackgroundColor="#080d08" Stroke="#22c55e" StrokeThickness="0.5" Padding="14">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="14"/></Border.StrokeShape>\n'
'            <VerticalStackLayout Spacing="4" HorizontalOptions="Center">\n'
'              <Label Text="TOTAL" FontSize="9" FontAttributes="Bold" TextColor="#22c55e" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding WeeklySummary.TotalHours, StringFormat={}{0:F1}h}" FontSize="24"\n'
'                     FontAttributes="Bold" TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Border>\n'
'        </Grid>\n'
'\n'
'        <Label Text="RECENT ENTRIES" FontSize="11" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'\n'
'        <CollectionView x:Name="TimesheetList"\n'
'                        ItemsSource="{Binding Timesheets}"\n'
'                        SelectionMode="Single"\n'
'                        SelectionChanged="TimesheetList_SelectionChanged">\n'
'          <CollectionView.ItemTemplate>\n'
'            <DataTemplate>\n'
'              <Border BackgroundColor="#0d0b05" Stroke="#1a1500" StrokeThickness="1"\n'
'                      Padding="18,14" Margin="0,0,0,10">\n'
'                <Border.StrokeShape><RoundRectangle CornerRadius="16"/></Border.StrokeShape>\n'
'                <Grid ColumnDefinitions="*,Auto">\n'
'                  <VerticalStackLayout Grid.Column="0" Spacing="4">\n'
'                    <Label Text="{Binding ProjectName}" FontAttributes="Bold"\n'
'                           FontSize="15" TextColor="#ffffff"/>\n'
'                    <Label Text="{Binding EmployeeName}" FontSize="12" TextColor="#888"/>\n'
'                    <Label Text="{Binding Date, StringFormat={}{0:MMM d, yyyy}}" FontSize="12" TextColor="#444"/>\n'
'                  </VerticalStackLayout>\n'
'                  <VerticalStackLayout Grid.Column="1" HorizontalOptions="End" Spacing="4">\n'
'                    <Label Text="{Binding HoursWorked, StringFormat={}{0:F1}h}" FontAttributes="Bold"\n'
'                           FontSize="18" TextColor="#f0a500" HorizontalOptions="End"/>\n'
'                    <Label Text="{Binding Status}" FontSize="11" TextColor="#555" HorizontalOptions="End"/>\n'
'                    <Label Text="&gt;" FontSize="14" TextColor="#f0a500" HorizontalOptions="End"/>\n'
'                  </VerticalStackLayout>\n'
'                </Grid>\n'
'              </Border>\n'
'            </DataTemplate>\n'
'          </CollectionView.ItemTemplate>\n'
'        </CollectionView>\n'
'\n'
'        <BoxView HeightRequest="80" Color="Transparent"/>\n'
'      </VerticalStackLayout>\n'
'    </ScrollView>\n'
'  </RefreshView>\n'
'</ContentPage>\n'
)

# ─────────────────────────────────────────────────────────────────────────────
# TimesheetPage.xaml.cs
# ─────────────────────────────────────────────────────────────────────────────
TS_CS = os.path.join(VIEWS, "TimesheetPage.xaml.cs")
TS_CS_TEXT = (
'#pragma warning disable CA1416\n'
'using BuildForce.Models;\n'
'using BuildForce.ViewModels;\n'
'\n'
'namespace BuildForce.Views;\n'
'\n'
'public partial class TimesheetPage : ContentPage\n'
'{\n'
'    readonly TimesheetViewModel _vm;\n'
'\n'
'    public TimesheetPage(TimesheetViewModel vm)\n'
'    {\n'
'        InitializeComponent();\n'
'        _vm = vm;\n'
'        BindingContext = vm;\n'
'    }\n'
'\n'
'    protected override async void OnAppearing()\n'
'    {\n'
'        base.OnAppearing();\n'
'        await _vm.LoadAsync();\n'
'    }\n'
'\n'
'    private async void TimesheetList_SelectionChanged(object sender, SelectionChangedEventArgs e)\n'
'    {\n'
'        if (e.CurrentSelection.FirstOrDefault() is not TimesheetDto selected)\n'
'            return;\n'
'\n'
'        ((CollectionView)sender).SelectedItem = null;\n'
'\n'
'        await Shell.Current.GoToAsync($"TimesheetDetailPage?timesheetId={selected.TimesheetId}");\n'
'    }\n'
'}\n'
)

# ─────────────────────────────────────────────────────────────────────────────
# TimesheetDetailPage.xaml
# ─────────────────────────────────────────────────────────────────────────────
TSD_XAML = os.path.join(VIEWS, "TimesheetDetailPage.xaml")
TSD_XAML_TEXT = (
'<?xml version="1.0" encoding="utf-8" ?>\n'
'<ContentPage\n'
'    x:Class="BuildForce.Views.TimesheetDetailPage"\n'
'    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"\n'
'    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"\n'
'    Title="Timesheet Detail"\n'
'    BackgroundColor="#080806"\n'
'    Shell.NavBarIsVisible="True"\n'
'    Shell.TabBarIsVisible="False">\n'
'  <ScrollView>\n'
'    <VerticalStackLayout Padding="20,16" Spacing="16">\n'
'\n'
'      <!-- HEADER CARD -->\n'
'      <Border BackgroundColor="#0d0b05" Stroke="#f0a500" StrokeThickness="1.5" Padding="24,22">\n'
'        <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'        <VerticalStackLayout Spacing="12">\n'
'          <Label Text="{Binding ProjectName}" FontSize="22" FontAttributes="Bold"\n'
'                 TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'          <Label Text="{Binding DateDisplay}" FontSize="13" TextColor="#888"\n'
'                 HorizontalOptions="Center"/>\n'
'          <Border BackgroundColor="#0a0800" Padding="16,8" HorizontalOptions="Center"\n'
'                  Stroke="{Binding StatusColor}">\n'
'            <Border.StrokeShape><RoundRectangle CornerRadius="20"/></Border.StrokeShape>\n'
'            <Label Text="{Binding StatusDisplay}" FontSize="13" FontAttributes="Bold"\n'
'                   TextColor="{Binding StatusColor}" HorizontalOptions="Center"/>\n'
'          </Border>\n'
'          <Label Text="{Binding DurationDisplay}" FontSize="42" FontAttributes="Bold"\n'
'                 TextColor="#f0a500" HorizontalOptions="Center" Margin="0,8,0,0"/>\n'
'          <Label Text="TOTAL DURATION" FontSize="10" TextColor="#555" HorizontalOptions="Center"/>\n'
'        </VerticalStackLayout>\n'
'      </Border>\n'
'\n'
'      <!-- EMPLOYEE CARD -->\n'
'      <Border BackgroundColor="#0d0b05" Stroke="#1a1500" StrokeThickness="1" Padding="20,16">\n'
'        <Border.StrokeShape><RoundRectangle CornerRadius="16"/></Border.StrokeShape>\n'
'        <VerticalStackLayout Spacing="10">\n'
'          <Label Text="EMPLOYEE" FontSize="10" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'          <Label Text="{Binding EmployeeName}" FontSize="17" FontAttributes="Bold" TextColor="#ffffff"/>\n'
'        </VerticalStackLayout>\n'
'      </Border>\n'
'\n'
'      <!-- CLOCK IN / OUT -->\n'
'      <Border BackgroundColor="#0d0b05" Stroke="#1a1500" StrokeThickness="1" Padding="20,16">\n'
'        <Border.StrokeShape><RoundRectangle CornerRadius="16"/></Border.StrokeShape>\n'
'        <VerticalStackLayout Spacing="14">\n'
'          <Label Text="TIME DETAILS" FontSize="10" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'          <Grid ColumnDefinitions="*,*" RowDefinitions="Auto,Auto" RowSpacing="4" ColumnSpacing="12">\n'
'            <Label Grid.Column="0" Grid.Row="0" Text="CLOCK IN" FontSize="10" TextColor="#555"/>\n'
'            <Label Grid.Column="1" Grid.Row="0" Text="CLOCK OUT" FontSize="10" TextColor="#555"/>\n'
'            <Label Grid.Column="0" Grid.Row="1" Text="{Binding ClockInDisplay}"\n'
'                   FontSize="20" FontAttributes="Bold" TextColor="#10b981"/>\n'
'            <Label Grid.Column="1" Grid.Row="1" Text="{Binding ClockOutDisplay}"\n'
'                   FontSize="20" FontAttributes="Bold" TextColor="#ef4444"/>\n'
'          </Grid>\n'
'        </VerticalStackLayout>\n'
'      </Border>\n'
'\n'
'      <!-- HOURS BREAKDOWN -->\n'
'      <Border BackgroundColor="#0d0b05" Stroke="#1a1500" StrokeThickness="1" Padding="20,16">\n'
'        <Border.StrokeShape><RoundRectangle CornerRadius="16"/></Border.StrokeShape>\n'
'        <VerticalStackLayout Spacing="14">\n'
'          <Label Text="HOURS BREAKDOWN" FontSize="10" FontAttributes="Bold" TextColor="#f0a500"/>\n'
'          <Grid ColumnDefinitions="*,*,*" ColumnSpacing="10">\n'
'            <VerticalStackLayout Grid.Column="0" Spacing="4" HorizontalOptions="Center">\n'
'              <Label Text="REGULAR" FontSize="9" TextColor="#f0a500" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding RegularHours}" FontSize="22" FontAttributes="Bold"\n'
'                     TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'            <VerticalStackLayout Grid.Column="1" Spacing="4" HorizontalOptions="Center">\n'
'              <Label Text="OVERTIME" FontSize="9" TextColor="#ef4444" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding OvertimeHours}" FontSize="22" FontAttributes="Bold"\n'
'                     TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'            <VerticalStackLayout Grid.Column="2" Spacing="4" HorizontalOptions="Center">\n'
'              <Label Text="TOTAL" FontSize="9" TextColor="#22c55e" HorizontalOptions="Center"/>\n'
'              <Label Text="{Binding TotalHours}" FontSize="22" FontAttributes="Bold"\n'
'                     TextColor="#ffffff" HorizontalOptions="Center"/>\n'
'            </VerticalStackLayout>\n'
'          </Grid>\n'
'        </VerticalStackLayout>\n'
'      </Border>\n'
'\n'
'      <!-- ACTION BUTTONS -->\n'
'      <Button Text="Approve Timesheet"\n'
'              Command="{Binding ApproveCommand}"\n'
'              BackgroundColor="#8b5cf6"\n'
'              TextColor="#ffffff" FontAttributes="Bold" FontSize="16"\n'
'              CornerRadius="14" HeightRequest="56"\n'
'              IsVisible="{Binding IsCompleted}"/>\n'
'\n'
'      <Button Text="Delete Entry"\n'
'              Command="{Binding DeleteCommand}"\n'
'              BackgroundColor="#1a0505" BorderColor="#ef4444" BorderWidth="1"\n'
'              TextColor="#ef4444" FontSize="15"\n'
'              CornerRadius="14" HeightRequest="48"/>\n'
'\n'
'      <BoxView HeightRequest="40" Color="Transparent"/>\n'
'    </VerticalStackLayout>\n'
'  </ScrollView>\n'
'</ContentPage>\n'
)

# ─────────────────────────────────────────────────────────────────────────────
# TimesheetDetailPage.xaml.cs
# ─────────────────────────────────────────────────────────────────────────────
TSD_CS = os.path.join(VIEWS, "TimesheetDetailPage.xaml.cs")
TSD_CS_TEXT = (
'#pragma warning disable CA1416\n'
'using BuildForce.ViewModels;\n'
'\n'
'namespace BuildForce.Views;\n'
'\n'
'public partial class TimesheetDetailPage : ContentPage\n'
'{\n'
'    readonly TimesheetDetailViewModel _vm;\n'
'\n'
'    public TimesheetDetailPage(TimesheetDetailViewModel vm)\n'
'    {\n'
'        InitializeComponent();\n'
'        _vm = vm;\n'
'        BindingContext = vm;\n'
'    }\n'
'}\n'
)

# ─────────────────────────────────────────────────────────────────────────────
# Write all files as raw bytes (no BOM, clean UTF-8)
# ─────────────────────────────────────────────────────────────────────────────
write(TS_XAML,  TS_XAML_TEXT)
write(TS_CS,    TS_CS_TEXT)
write(TSD_XAML, TSD_XAML_TEXT)
write(TSD_CS,   TSD_CS_TEXT)

print("\nAll done! Build and deploy to Samsung.")